# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/learn-pytorch',
                'doc_host': 'https://deven367.github.io',
                'git_url': 'https://github.com/deven367/learn-pytorch',
                'lib_path': 'learn_pytorch'},
  'syms': {'learn_pytorch.core': {'learn_pytorch.core.foo': ('core.html#foo', 'learn_pytorch/core.py')}}}
