# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/learning-pytorch',
                'doc_host': 'https://deven367.github.io',
                'git_url': 'https://github.com/deven367/learning-pytorch',
                'lib_path': 'learn_pytorch'},
  'syms': { 'learn_pytorch.core': {'learn_pytorch.core.foo': ('core.html#foo', 'learn_pytorch/core.py')},
            'learn_pytorch.helper': { 'learn_pytorch.helper.accuracy_fn': ( '02-nn-classification.html#accuracy_fn',
                                                                            'learn_pytorch/helper.py')}}}
