# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02-nn-classification.ipynb.

# %% auto 0
__all__ = ['accuracy_fn']

# %% ../nbs/02-nn-classification.ipynb 4
import torch
import torch.nn as nn

# %% ../nbs/02-nn-classification.ipynb 21
# Calculate accuracy (a classification metric)
def accuracy_fn(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item() # torch.eq() calculates where two tensors are equal
    acc = (correct / len(y_pred)) * 100
    return acc
